spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: ldncs
    password: 66666
  h2:
    console:
      settings:
        trace: true
        web-allow-others: true
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
  sql:
    init:
      schema-locations: classpath:db/table.sql
      data-locations: classpath:db/data.sql

mybatis:
  mapper-locations: classpath:/fusion/*.xml, classpath:/decision/*.xml, classpath:/access/*.xml