spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.21.32.98:3306/data_fusion?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

  mvc:
    servlet:
      load-on-startup: 1

  sql:
    init:
      schema-locations: classpath:db/table.sql
      data-locations: classpath:db/init.sql
      mode: always

  kafka:
    bootstrap-servers: 8.134.59.53:9092
    consumer:
      group-id: topic_data_service_original_message_group
      auto-offset-reset: latest
    streams:
      auto-startup: false


mybatis:
  mapper-locations: classpath:/fusion/*.xml, classpath:/decision/*.xml, classpath:/access/*.xml